### ISSUE TITLE
Request for Increased Collaboration and Pull Request Acceptance in Repository

### ISSUE THREAD

**Issue by Bugz-gg** [PoroCoco/Fluid-Sim#3]
Hello M.PunaiseDe,

I hope this message find you well, Im writing this Issue due to the of work you put in this repository. You barrely accept pull request and you have like 1 or 2 commits. Please wake up, I know you are trying to switch to the Tokyo time zone so you may will see this too late but anyway.

Best regard,
Your Best friend.

**Comment by UnePatate5010** [comment]
![image](https://github.com/PoroCoco/Fluid-Sim/assets/95414227/9b5380af-f202-484d-972a-228767e302fa)
